#!/usr/bin/env python3
from __future__ import annotations

import hashlib
import json
import re
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path.cwd()
TEMPLATE = ROOT / "apps/web/app/templates/campaign/index.html"
CSS_DIR = ROOT / "apps/web/app/static/css"
BUNDLE_NAME = "campaign.bundle.css"
BUNDLE_PATH = CSS_DIR / BUNDLE_NAME
PROOF_PATH = ROOT / "docs/release-proof/campaign-single-css-bundle-latest.json"

CSS_REF_RE = re.compile(r"filename\s*=\s*['\"]css/([^'\"]+\.css)['\"]")
CSS_LINK_TAG_RE = re.compile(
    r"\n?[ \t]*<link\b(?=[^>]*filename\s*=\s*['\"]css/[^'\"]+\.css['\"])[^>]*>\s*",
    re.S,
)

DEFAULT_SOURCE_STACK = [
    "ff.css",
    "campaign.css",
    "campaign.unified.css",
    "ff-launch-completion.css",
    "ff-campaign-enterprise.css",
    "ff-fortune500-final.css",
    "ff-campaign-final-compression.css",
]


def unique_in_order(items: list[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for item in items:
        if item not in seen:
            out.append(item)
            seen.add(item)
    return out


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def sha(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8", errors="replace")).hexdigest()


def main() -> None:
    if not TEMPLATE.exists():
        raise SystemExit(f"Missing template: {TEMPLATE}")

    html = read(TEMPLATE)
    original_html = html

    linked_css = unique_in_order(CSS_REF_RE.findall(html))

    if not linked_css:
        raise SystemExit("No linked CSS files found in campaign template.")

    # If rerun after the template already points to the single bundle, rebuild from known source stack.
    if linked_css == [BUNDLE_NAME]:
        source_css = DEFAULT_SOURCE_STACK
        rerun_mode = True
    else:
        source_css = [name for name in linked_css if name != BUNDLE_NAME]
        rerun_mode = False

    required_sources = {
        "ff.css",
        "campaign.css",
        "ff-campaign-final-compression.css",
    }
    missing_required_refs = sorted(required_sources - set(source_css))
    if missing_required_refs:
        raise SystemExit(
            "Refusing to build bundle because expected source refs are missing: "
            + ", ".join(missing_required_refs)
        )

    source_reports = []
    bundle_parts = [
        f"""/*
  FutureFunded Campaign Single CSS Bundle
  File: apps/web/app/static/css/{BUNDLE_NAME}
  Generated: {datetime.now(timezone.utc).isoformat()}

  Purpose:
  - One campaign template stylesheet for the public campaign route.
  - Preserves original source order.
  - Keeps original source files in repo for rollback/provenance.
  - Do not edit this file manually; regenerate with scripts/release/ff_campaign_single_css_bundle.py.

  Source order:
{chr(10).join(f"  - {name}" for name in source_css)}
*/

/* FF_CAMPAIGN_SINGLE_CSS_BUNDLE_START */
"""
    ]

    missing_files = []

    for index, name in enumerate(source_css, start=1):
        path = CSS_DIR / name
        if not path.exists():
            missing_files.append(name)
            continue

        css = read(path).rstrip()
        source_reports.append(
            {
                "order": index,
                "file": name,
                "path": str(path.relative_to(ROOT)),
                "lines": css.count("\n") + 1,
                "bytes": len(css.encode("utf-8", errors="replace")),
                "sha256": sha(css),
            }
        )

        bundle_parts.append(
            f"""
/* ==========================================================================
   BEGIN SOURCE {index}: {name}
   Path: {path.relative_to(ROOT)}
   ========================================================================== */

{css}

/* ==========================================================================
   END SOURCE {index}: {name}
   ========================================================================== */
"""
        )

    if missing_files:
        raise SystemExit("Missing source CSS files: " + ", ".join(missing_files))

    bundle_parts.append("\n/* FF_CAMPAIGN_SINGLE_CSS_BUNDLE_END */\n")
    bundle_text = "\n".join(bundle_parts).rstrip() + "\n"
    BUNDLE_PATH.write_text(bundle_text, encoding="utf-8")

    # Remove every CSS link tag in campaign template and insert exactly one bundle preload + stylesheet.
    matches = list(CSS_LINK_TAG_RE.finditer(html))
    if not matches:
        raise SystemExit("Could not find CSS <link> tags to replace.")

    insert_at = matches[0].start()

    html_without_css = CSS_LINK_TAG_RE.sub("", html)

    source_contract = " ".join(source_css)
    bundle_links = f"""
  <!-- FF_CAMPAIGN_SINGLE_CSS_BUNDLE_SOURCES: {source_contract} -->
  <link
    rel="preload"
    as="style"
    href="{{{{ url_for('static', filename='css/{BUNDLE_NAME}') }}}}?v={{{{ _asset_v|default(asset_v|default('campaign-single-css-bundle', true), true)|e }}}}"
    data-ff-page-css-preload="{BUNDLE_NAME}"
    data-ff-bundle-sources="{source_contract}"
  />
  <link
    rel="stylesheet"
    href="{{{{ url_for('static', filename='css/{BUNDLE_NAME}') }}}}?v={{{{ _asset_v|default(asset_v|default('campaign-single-css-bundle', true), true)|e }}}}"
    data-ff-page-css="{BUNDLE_NAME}"
    data-ff-checkout-css-contract
    data-ff-campaign-bundle-css
    data-ff-bundle-sources="{source_contract}"
  />
"""

    html = html_without_css[:insert_at] + bundle_links + html_without_css[insert_at:]

    required_html = [
        BUNDLE_NAME,
        "FF_CAMPAIGN_SINGLE_CSS_BUNDLE_SOURCES",
        "ff.css",
        "campaign.css",
        "ff-campaign-final-compression.css",
        "ffCampaignConfig",
        "ffSponsorContract",
        "ff-campaign.js",
        "data-ff-open-checkout",
        "data-ff-open-sponsor",
        "data-ff-share-trigger",
    ]

    missing_html = [item for item in required_html if item not in html]
    if missing_html:
        raise SystemExit("Missing required campaign template contracts: " + ", ".join(missing_html))

    forbidden_link_refs = [
        "css/ff.css",
        "css/campaign.css",
        "css/campaign.unified.css",
        "css/campaign.css",
        "css/campaign.authority.css",
        "css/ff-launch-completion.css",
        "css/ff-campaign-enterprise.css",
        "css/ff-fortune500-final.css",
        "css/ff-campaign-final-compression.css",
    ]

    # Only the bundle href should remain as a css/ link. Source names may remain in comments/data attrs without css/ prefix.
    still_linked = [ref for ref in forbidden_link_refs if ref in html]
    if still_linked:
        raise SystemExit("Old CSS href references still present: " + ", ".join(still_linked))

    if html != original_html:
        TEMPLATE.write_text(html, encoding="utf-8")

    proof = {
        "generatedAt": datetime.now(timezone.utc).isoformat(),
        "rerunMode": rerun_mode,
        "template": str(TEMPLATE.relative_to(ROOT)),
        "bundle": str(BUNDLE_PATH.relative_to(ROOT)),
        "bundleLines": bundle_text.count("\n") + 1,
        "bundleBytes": len(bundle_text.encode("utf-8", errors="replace")),
        "bundleSha256": sha(bundle_text),
        "sourceCss": source_css,
        "sourceReports": source_reports,
        "templateCssLinksAfter": unique_in_order(CSS_REF_RE.findall(html)),
    }

    PROOF_PATH.parent.mkdir(parents=True, exist_ok=True)
    PROOF_PATH.write_text(json.dumps(proof, indent=2), encoding="utf-8")

    print(json.dumps(
        {
            "bundle": proof["bundle"],
            "bundleLines": proof["bundleLines"],
            "sourceCss": proof["sourceCss"],
            "templateCssLinksAfter": proof["templateCssLinksAfter"],
            "proof": str(PROOF_PATH.relative_to(ROOT)),
        },
        indent=2,
    ))


if __name__ == "__main__":
    main()
